Update kaleidoglyph-builder from kaleidoscope-builder
I copied the recent changes from Kaleidoscope that speeds up builds by cachine results,
but preserved the minor changes that I made for building Kaleidoglyph (C++14, mostly).

Signed-off-by: Michael Richters <gedankenexperimenter@gmail.com>

diff --git a/bin/kaleidoglyph-builder b/bin/kaleidoglyph-builder
--- a/bin/kaleidoglyph-builder
+++ b/bin/kaleidoglyph-builder
@@ -1,4 +1,20 @@
-#! /bin/sh
+#!/usr/bin/env bash
+
+# Almost entirely copied from kaleidoscope-builder:
+
+# kaleidoscope-builder - Kaleidoscope helper tool
+# Copyright (C) 2017-2018  Keyboard.io, Inc.
+#
+# This program is free software: you can redistribute it and/or modify it under
+# the terms of the GNU General Public License as published by the Free Software
+# Foundation, version 3.
+#
+# This program is distributed in the hope that it will be useful, but WITHOUT
+# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
+# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License along with
+# this program. If not, see <http://www.gnu.org/licenses/>.
 
 set -e
 
@@ -7,12 +23,32 @@ set -e
 ######
 
 build_version () {
-    GIT_VERSION="$(cd $(find_sketch); git describe --abbrev=4 --dirty --always)"
-    LIB_VERSION="$(cd $(find_sketch); (grep version= ../../library.properties 2>/dev/null || echo version=0.0.0) | cut -d= -f2)-g${GIT_VERSION}"
+    GIT_VERSION="$(cd "$(find_sketch)"; if [ -d .git ]; then echo '-g' && git describe --abbrev=4 --dirty --always; fi)"
+    LIB_PROPERTIES_PATH="${LIB_PROPERTIES_PATH:-"../.."}"
+    LIB_VERSION="$(cd "$(find_sketch)"; (grep version= "${LIB_PROPERTIES_PATH}/library.properties" 2>/dev/null || echo version=0.0.0) | cut -d= -f2)${GIT_VERSION}"
+}
 
-    BUILD_PATH="${BUILD_PATH:-$(mktemp -d 2>/dev/null || mktemp -d -t 'build')}"
-    OUTPUT_DIR="${OUTPUT_DIR:-output/${LIBRARY}}"
-    OUTPUT_PATH="${OUTPUT_PATH:-${SOURCEDIR}/${OUTPUT_DIR}}"
+build_paths() {
+    # We don't really want to use find
+    # shellcheck disable=SC2012
+    SKETCH_IDENTIFIER="$(ls -id "$(find_sketch)/${SKETCH}.ino" | cut -d ' ' -f 1)-${SKETCH}.ino"
+    KALEIDOGLYPH_TEMP_PATH="${KALEIDOGLYPH_TEMP_PATH:-${TMPDIR:-/tmp}/kaleidoglyph-${USER}}"
+
+
+    KALEIDOGLYPH_BUILD_PATH="${KALEIDOGLYPH_BUILD_PATH:-${KALEIDOGLYPH_TEMP_PATH}/sketch}"
+    KALEIDOGLYPH_OUTPUT_PATH="${KALEIDOGLYPH_OUTPUT_PATH:-${KALEIDOGLYPH_TEMP_PATH}/sketch}"
+
+    SKETCH_OUTPUT_DIR="${SKETCH_OUTPUT_DIR:-${SKETCH_IDENTIFIER}/output}"
+    SKETCH_BUILD_DIR="${SKETCH_BUILD_DIR:-${SKETCH_IDENTIFIER}/build}"
+
+    BUILD_PATH="${BUILD_PATH:-${KALEIDOGLYPH_BUILD_PATH}/${SKETCH_BUILD_DIR}}"
+    OUTPUT_PATH="${OUTPUT_PATH:-${KALEIDOGLYPH_OUTPUT_PATH}/${SKETCH_OUTPUT_DIR}}"
+
+    CCACHE_WRAPPER_PATH="${CCACHE_WRAPPER_PATH:-${KALEIDOGLYPH_TEMP_PATH}/ccache/bin}"
+    CORE_CACHE_PATH="${CORE_CACHE_PATH:-${KALEIDOGLYPH_TEMP_PATH}/arduino-cores}"
+
+    mkdir -p "$CORE_CACHE_PATH"
+    mkdir -p "$BUILD_PATH"
 }
 
 build_filenames () {
@@ -22,24 +58,53 @@ build_filenames () {
     ELF_FILE_PATH="${OUTPUT_PATH}/${OUTPUT_FILE_PREFIX}.elf"
 }
 
+
+enable_ccache () {
+    if  [ "$(command -v ccache)" ]; then
+    if ! [ -d "$CCACHE_WRAPPER_PATH" ]; then
+	mkdir -p "$CCACHE_WRAPPER_PATH"
+	ln -s "$(command -v ccache)" "${CCACHE_WRAPPER_PATH}/${COMPILER_PREFIX}gcc"
+	ln -s "$(command -v ccache)" "${CCACHE_WRAPPER_PATH}/${COMPILER_PREFIX}g++"
+	ln -s "${AVR_NM}" "${CCACHE_WRAPPER_PATH}/${COMPILER_PREFIX}nm"
+	ln -s "${AVR_OBJCOPY}" "${CCACHE_WRAPPER_PATH}/${COMPILER_PREFIX}objcopy"
+	ln -s "${AVR_AR}" "${CCACHE_WRAPPER_PATH}/${COMPILER_PREFIX}ar"
+	ln -s "${AVR_SIZE}" "${CCACHE_WRAPPER_PATH}/${COMPILER_PREFIX}size"
+    fi
+    export CCACHE_PATH=${COMPILER_PATH}/
+    CCACHE_ENABLE="-prefs compiler.path=${CCACHE_WRAPPER_PATH}/"
+    fi
+}
+
+
 firmware_size () {
     if [ "${BOARD}" = "virtual" ]; then
-	echo "[Size not computed for virtual build]"
-	return
+        echo "[Size not computed for virtual build]"
+        return
     fi
 
     ## This is a terrible hack, please don't hurt me. - algernon
 
-    MAX_PROG_SIZE=28672
+    find_max_prog_size
+    set +e
+    raw_output=$("$@" 2> /dev/null)
+    rc=$?
+    set -e
 
-    output="$($@ | grep "\\(Program\\|Data\\):" | sed -e 's,^,  - ,' && echo)"
+    if [ $rc -eq 0 ]; then
+        output="$(echo "${raw_output}"| grep "\\(Program\\|Data\\):" | sed -e 's,^,  - ,' && echo)"
 
-    PROGSIZE="$(echo "${output}" | grep Program: | cut -d: -f2 | awk '{print $1}')"
+        PROGSIZE="$(echo "${output}" | grep "Program:" | cut -d: -f2 | awk '{print $1}')"
 
-    PERCENT="$(echo ${PROGSIZE} ${MAX_PROG_SIZE} | awk "{ printf \"%02.01f\", \$1 / \$2 * 100 }")"
+        PERCENT="$(echo "${PROGSIZE}" "${MAX_PROG_SIZE}" | awk "{ printf \"%02.01f\", \$1 / \$2 * 100 }")"
 
-    echo "${output}" | sed -e "s/\(Program:.*\)(\([0-9\.]*%\) Full)/\1(${PERCENT}% Full)/"
+        # we want the sed there, doing with shell builtins would be worse.
+        # shellcheck disable=SC2001 disable=SC1117
+        echo "${output}" | sed -e "s/\(Program:.*\)(\([0-9\.]*%\) Full)/\1(${PERCENT}% Full)/"
+    else
+        echo "Unable to determine image size."
+    fi
 }
+
 
 find_sketch () {
     SKETCH="${SKETCH:-${DEFAULT_SKETCH}}"
@@ -57,7 +122,7 @@ find_sketch () {
             return
         fi
     done
-    echo "Couldn't find sketch (.ino file)" >&2
+    echo "I couldn't find your sketch (.ino file)" >&2
     exit 1
 }
 
@@ -67,31 +132,52 @@ prepare_to_flash () {
         size
     fi
 
-    echo "Press ENTER when ready..."
-    read a
+    echo "To update your keyboard's firmware, hold down the 'Prog' key on your keyboard,"
+    echo "and then press 'Enter'."
+    echo ""
+    echo "When the 'Prog' key glows red, you can release it."
+    echo ""
+
+    # We do not want to permit line continuations here. We just want a newline.
+    # shellcheck disable=SC2162
+    read
 }
 
 flash () {
     prepare_to_flash
+
+    # This is defined in the (optional) user config.
+    # shellcheck disable=SC2154
+    ${preFlash_HOOKS}
+
     reset_device
-    sleep 3s
+    sleep 3
     find_bootloader_ports
+    check_bootloader_port_and_flash
+
+    # This is defined in the (optional) user config.
+    # shellcheck disable=SC2154
+    ${postFlash_HOOKS}
+}
+
+
+check_bootloader_port_and_flash () {
+    if [ -z "${DEVICE_PORT_BOOTLOADER}" ]; then
+        echo "Unable to detect a keyboard in bootloader mode. You may need to hold the 'Prog' key or hit a reset button"
+        return 1
+    fi
     flash_over_usb || flash_over_usb
 }
 
 flash_over_usb () {
-    if [ -z "${DEVICE_PORT_BOOTLOADER}" ]; then
-        echo 'DEVICE_PORT_BOOTLOADER is empty (did you hold "Prog" to enable bootloader mode?)' >&2
-        return 1
-    fi
-    sleep 1s
-    ${AVRDUDE} -q -q -C ${AVRDUDE_CONF} -p${MCU} -cavr109 -D -P ${DEVICE_PORT_BOOTLOADER} -b57600 "-Uflash:w:${HEX_FILE_PATH}:i"
+    sleep 1
+    ${AVRDUDE} -q -q -C "${AVRDUDE_CONF}" -p"${MCU}" -cavr109 -D -P "${DEVICE_PORT_BOOTLOADER}" -b57600 "-Uflash:w:${HEX_FILE_PATH}:i"
 }
 
 flash_from_bootloader() {
     prepare_to_flash
     find_bootloader_ports
-    flash_over_usb || flash_over_usb
+    check_bootloader_port_and_flash
 }
 
 program() {
@@ -101,8 +187,8 @@ program() {
 
 flash_with_programmer() {
     ${AVRDUDE} -v \
-	       -C ${AVRDUDE_CONF} \
-	       -p${MCU} \
+	       -C "${AVRDUDE_CONF}" \
+	       -p"${MCU}" \
 	       -cusbtiny \
 	       -D \
 	       -B 1 \
@@ -114,84 +200,122 @@ hex_with_bootloader () {
         compile
     fi
 
-    cat ${HEX_FILE_PATH} | awk '/^:00000001FF/ == 0' > ${HEX_FILE_WITH_BOOTLOADER_PATH}
+    awk '/^:00000001FF/ == 0' "${HEX_FILE_PATH}" > "${HEX_FILE_WITH_BOOTLOADER_PATH}"
     echo "Using ${BOOTLOADER_PATH}"
-    ${MD5} ${BOOTLOADER_PATH}
-    cat ${BOOTLOADER_PATH} >> ${HEX_FILE_WITH_BOOTLOADER_PATH}
-    ln -sf "${HEX_FILE_WITH_BOOTLOADER_PATH}" "${OUTPUT_PATH}/${SKETCH}-latest-with-bootloader.hex"
-    cat <<EOF
+    ${MD5} "${BOOTLOADER_PATH}"
+    cat "${BOOTLOADER_PATH}" >> "${HEX_FILE_WITH_BOOTLOADER_PATH}"
+    ln -sf -- "${HEX_FILE_WITH_BOOTLOADER_PATH}" "${OUTPUT_PATH}/${SKETCH}-latest-with-bootloader.hex"
+    cat <<- EOF
 
-Combined firmware and bootloader are now at ${HEX_FILE_WITH_BOOTLOADER_PATH}
-Make sure you have the bootloader version you expect.
+		Combined firmware and bootloader are now at ${HEX_FILE_WITH_BOOTLOADER_PATH}
+		Make sure you have the bootloader version you expect.
 
-And TEST THIS ON REAL HARDWARE BEFORE YOU GIVE IT TO ANYONE
+		And TEST THIS ON REAL HARDWARE BEFORE YOU GIVE IT TO ANYONE
 
-EOF
+		EOF
 }
 
 build () {
-    compile $@
-    size $@
+    compile "$@"
+    size "$@"
 }
 
 compile () {
     build_version
+    build_paths
     build_filenames
-    install -d "${OUTPUT_PATH}"
+    enable_ccache
 
-    echo "Building ${OUTPUT_DIR}/${SKETCH} (${LIB_VERSION}) ..."
+    install -d "${OUTPUT_PATH}"
+    
+    SKETCH_DIR="$(find_sketch)"
+
+    echo "Building ${SKETCH_DIR}/${SKETCH} ${LIB_VERSION} into ${OUTPUT_PATH}..."
+
+    # This is defined in the (optional) user config.
+    # shellcheck disable=SC2154
     ${compile_HOOKS}
 
     if [ -d "${ARDUINO_LOCAL_LIB_PATH}/libraries" ]; then
+        # shellcheck disable=SC2089
+        # We want literal backslashes here, not arrays.
         local_LIBS="-libraries \"${ARDUINO_LOCAL_LIB_PATH}/libraries\""
     fi
 
     ARDUINO_PACKAGES=""
-    if [ -d ${ARDUINO_PACKAGE_PATH} ]; then
-	ARDUINO_PACKAGES="-hardware \"${ARDUINO_PACKAGE_PATH}\""
+    if [ -d "${ARDUINO_PACKAGE_PATH}" ]; then
+        # shellcheck disable=SC2089
+        # We want literal backslashes here, not arrays.
+	      ARDUINO_PACKAGES="-hardware \"${ARDUINO_PACKAGE_PATH}\""
     fi
 
+    SAVED_BOARD="${BOARD}"
+    SAVED_FQBN="${FQBN}"
+    if [ -e "${SKETCH_DIR}/.kaleidoglyph-builder.conf" ]; then
+        # shellcheck disable=SC1090
+        BOARD="$(. "${SKETCH_DIR}"/.kaleidoglyph-builder.conf && echo "${BOARD}")"
+        # shellcheck disable=SC1090
+        FQBN="$(. "${SKETCH_DIR}"/.kaleidoglyph-builder.conf && echo "${FQBN}")"
+        if [ "${SAVED_FQBN}" = "${FQBN}" ] || [ -z "${FQBN}" ]; then
+            FQBN="keyboardio:avr:${BOARD}"
+        fi
+    fi
+
+    # SC2091: We do not care if quotes or backslashes are not respected.
+    # SC2086: We want word splitting.
+    # shellcheck disable=SC2086,SC2090
     ${ARDUINO_BUILDER} \
         -compile \
-	${ARDUINO_PACKAGES} \
-	-hardware "${ARDUINO_PATH}/hardware" \
-	-hardware "${BOARD_HARDWARE_PATH}" \
-	${ARDUINO_TOOLS_PARAM} \
-	-tools "${ARDUINO_PATH}/tools-builder" \
-	-fqbn "${FQBN}" \
+	      ${ARDUINO_PACKAGES} \
+	      -hardware "${ARDUINO_PATH}/hardware" \
+	      -hardware "${BOARD_HARDWARE_PATH}" \
+	      ${ARDUINO_TOOLS_PARAM} \
+	      -tools "${ARDUINO_PATH}/tools-builder" \
+	      -fqbn "${FQBN}" \
         -libraries "." \
         -libraries "${ROOT}" \
-	-libraries "${BOARD_HARDWARE_PATH}/.." \
+	      -libraries "${BOARD_HARDWARE_PATH}/.." \
         ${local_LIBS} \
-	${EXTRA_BUILDER_ARGS} \
-	-build-path "${BUILD_PATH}" \
-	-ide-version "${ARDUINO_IDE_VERSION}" \
-	-prefs "compiler.cpp.extra_flags=-std=c++14 -Woverloaded-virtual -Wno-ignored-qualifiers -Wno-sized-deallocation ${ARDUINO_CFLAGS} ${LOCAL_CFLAGS}" \
-	-warnings all \
+	      ${EXTRA_BUILDER_ARGS} \
+	      -build-cache "${CORE_CACHE_PATH}" \
+	      -build-path "${BUILD_PATH}" \
+	      -ide-version "${ARDUINO_IDE_VERSION}" \
+	      -prefs "compiler.cpp.extra_flags=-std=c++14 -Woverloaded-virtual -Wno-ignored-qualifiers -Wno-sized-deallocation ${ARDUINO_CFLAGS} ${LOCAL_CFLAGS}" \
+	      $CCACHE_ENABLE \
+	      -warnings all \
         ${ARDUINO_VERBOSE} \
-	${ARDUINO_AVR_GCC_PREFIX_PARAM} \
-	"$(find_sketch)/${SKETCH}.ino"
+	      ${ARDUINO_AVR_GCC_PREFIX_PARAM} \
+	      "${SKETCH_DIR}/${SKETCH}.ino"
 
     cp "${BUILD_PATH}/${SKETCH}.ino.hex" "${HEX_FILE_PATH}"
     cp "${BUILD_PATH}/${SKETCH}.ino.elf" "${ELF_FILE_PATH}"
     ln -sf "${OUTPUT_FILE_PREFIX}.hex" "${OUTPUT_PATH}/${SKETCH}-latest.hex"
     ln -sf "${OUTPUT_FILE_PREFIX}.elf" "${OUTPUT_PATH}/${SKETCH}-latest.elf"
 
+
     if [ "${ARDUINO_VERBOSE}" = "-verbose" ]; then
-	echo "Build artifacts can be found in ${BUILD_PATH}";
-    else
-	rm -rf "${BUILD_PATH}" 
-    fi 
+      echo "Build artifacts can be found in ${BUILD_PATH}";
+    fi
+
+    BOARD="${SAVED_BOARD}"
+    FQBN="${SAVED_FQBN}"
 }
 
 _find_all () {
     for plugin in ./*.ino \
-	    	      examples/* \
-                      src/*.ino; do
-        if [ -d "$(dirname ${plugin})" ] || [ -f "${plugin}" ]; then
+  	              $([ -d examples ] && find examples -name '*.ino') \
+                  src/*.ino; do
+        if [ -d "$(dirname "${plugin}")" ] || [ -f "${plugin}" ]; then
             p="$(basename "${plugin}" .ino)"
             if [ "${p}" != '*' ]; then
-                echo "${p}"
+                case "${plugin}" in
+                    examples/*/${p}/${p}.ino)
+                        echo "${plugin}" | sed -e "s,examples/,," | sed -e "s,/${p}\\.ino,,"
+                        ;;
+                    *)
+                        echo "${p}"
+                        ;;
+                esac
             fi
         fi
     done | sort
@@ -203,9 +327,21 @@ build_all () {
     for plugin in ${plugins}; do
         export SKETCH="${plugin}"
         export LIBRARY="${plugin}"
-        $0 ${plugin} build
+        $0 "${plugin}" build
     done
 }
+
+
+compile_all () {
+    plugins="$(_find_all)"
+
+    for plugin in ${plugins}; do
+        export SKETCH="${plugin}"
+        export LIBRARY="${plugin}"
+        $0 "${plugin}" compile
+    done
+}
+
 
 size () {
     if [ ! -e "${HEX_FILE_PATH}" ]; then
@@ -213,7 +349,8 @@ size () {
     fi
 
     echo "- Size: firmware/${LIBRARY}/${OUTPUT_FILE_PREFIX}.elf"
-    firmware_size "${AVR_SIZE}" -C --mcu="${MCU}" "${ELF_FILE_PATH}"
+    # shellcheck disable=SC2086
+    firmware_size "${AVR_SIZE}" ${AVR_SIZE_FLAGS} "${ELF_FILE_PATH}"
     echo
 }
 
@@ -239,7 +376,7 @@ decompile () {
 }
 
 clean () {
-    rm -rf "${OUTPUT_PATH}"
+    rm -rf -- "${OUTPUT_PATH}"
 }
 
 reset_device() {
@@ -249,54 +386,98 @@ reset_device() {
 }
 
 check_device_port () {
-    if [ -z $DEVICE_PORT ]; then
-        echo "Couldn't autodetect the keyboard's serial port."
-        echo "If you see this message and your keyboard is connected to your computer,"
-        echo "it probably means that our serial port detection logic is buggy or incomplete."
-        echo
-        echo "Please report this issue at https://github.com/keyboardio/Kaleidoglyph";
-        exit 0;
+    if [ -z "$DEVICE_PORT" ]; then
+        cat <<EOF >&2
+
+I couldn't autodetect the keyboard's serial port.
+
+If you see this message and your keyboard is connected to your computer,
+it may mean that our serial port detection logic is buggy or incomplete.
+In that case, please report this issue at:
+	 https://github.com/gedankenlab/Kaleidoglyph-Core
+EOF
+        exit 1
+    elif echo "$DEVICE_PORT" | grep -q '[[:space:]]'; then
+        cat <<EOF >&2
+Unexpected whitespace found in detected serial port:
+
+    $DEVICE_PORT
+
+If you see this message, it means that our serial port
+detection logic is buggy or incomplete.
+
+Please report this issue at:
+	 https://github.com/gedankenlab/Kaleidoglyph-Core
+EOF
+        exit 1
+    fi
+
+    if ! [ -w "$DEVICE_PORT" ]; then
+        cat <<EOF >&2
+
+In order to update your keyboard's firmware you need to have permission
+to write to its serial port $DEVICE_PORT.
+
+It appears that you do not have this permission:
+
+  $(ls -l "$DEVICE_PORT")
+
+This may be because you're not in the correct unix group:
+
+  $(stat -c %G "$DEVICE_PORT").
+
+You are currently in the following groups:
+
+  $(id -Gn)
+
+Please ensure you have followed the instructions on setting up your
+account to be in the right group:
+
+https://github.com/keyboardio/Kaleidoscope/wiki/Install-Arduino-support-on-Linux
+
+EOF
+        exit 1
     fi
 }
 
 usage () {
-    cat <<EOF
-Usage: $0 SKETCH commands...
+    cat <<- EOF
+		Usage: $0 SKETCH commands...
 
-Runs all of the commands in the context of the Sketch.
+		Runs all of the commands in the context of the Sketch.
 
-Available commands:
+		Available commands:
 
-  help
-    This help screen.
+		  help
+		    This help screen.
 
-  compile
-    Compiles the sketch.
+		  compile
+		    Compiles the sketch.
 
-  size
-    Reports the size of the compiled sketch.
+		  size
+		    Reports the size of the compiled sketch.
 
-  build
-    Runs compile and report-size.
+		  build
+		    Runs compile and report-size.
 
-  clean
-    Cleans up the output directory.
+		  clean
+		    Cleans up the output directory.
 
-  size-map
-    Displays the size map for the sketch.
+		  size-map
+		    Displays the size map for the sketch.
 
-  disassemble
-    Decompile the sketch.
+		  disassemble
+		    Decompile the sketch.
 
-  reset-device
-    Reset the device.
+		  reset-device
+		    Reset the device.
 
-  flash
-    Flashes the firmware using avrdude.
+		  flash
+		    Flashes the firmware using avrdude.
 
-  build-all
-    Build all Sketches we can find.
-EOF
+		  build-all
+		    Build all Sketches we can find.
+		EOF
 }
 
 help () {
@@ -315,23 +496,28 @@ fi
 ##
 ##  - if there is only one argument, that's a command
 
-ROOT="$(cd $(dirname $0)/..; pwd)"
+ROOT="$(cd "$(dirname "$0")"/..; pwd)"
 export ROOT
+# shellcheck disable=SC2155
 export SOURCEDIR="$(pwd)"
 
 if [ -e "${HOME}/.kaleidoglyph-builder.conf" ]; then
+    # shellcheck disable=SC1090
     . "${HOME}/.kaleidoglyph-builder.conf"
 fi
 
 if [ -e "${SOURCEDIR}/.kaleidoglyph-builder.conf" ]; then
+    # shellcheck disable=SC1090
     . "${SOURCEDIR}/.kaleidoglyph-builder.conf"
 fi
 
 if [ -e "${SOURCEDIR}/kaleidoglyph-builder.conf" ]; then
+    # shellcheck disable=SC1090
     . "${SOURCEDIR}/kaleidoglyph-builder.conf"
 fi
 
-. ${ROOT}/etc/kaleidoglyph-builder.conf
+# shellcheck disable=SC1090
+. "${ROOT}/etc/kaleidoglyph-builder.conf"
 
 if [ ! -z "${VERBOSE}" ] && [ "${VERBOSE}" -gt 0 ]; then
     ARDUINO_VERBOSE="-verbose"
@@ -348,6 +534,8 @@ for i in $(seq 1 $#); do
 
     case "${v}" in
         *=*)
+            # Exporting an expansion is *precisely* what we want here.
+            # shellcheck disable=SC2086,SC2163
             export ${v}
             ;;
         *)
@@ -356,10 +544,12 @@ for i in $(seq 1 $#); do
     esac
 done
 
+# Word splitting is desired here.
+# shellcheck disable=SC2086
 set -- ${cmds}
 
 if [ $# -eq 1 ]; then
-    cmd="$(echo $1 | tr '-' '_')"
+    cmd="$(echo "$1" | tr '-' '_')"
     ${cmd}
     exit $?
 fi
@@ -373,12 +563,19 @@ fi
 
 cmds=""
 
+# shellcheck disable=2034
 for i in $(seq 1 $#); do
-    cmds="${cmds} $(echo $1 | tr '-' '_')"
+    cmds="${cmds} $(echo "$1" | tr '-' '_')"
     shift
 done
 
 LIBRARY="${SKETCH}"
+
+case "${SKETCH}" in
+    */*)
+        SKETCH="$(basename "${SKETCH}")"
+        ;;
+esac
 
 export SKETCH
 export LIBRARY
